services:
  # API Gateway
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    env_file:
      - ./gateway/.env
    networks:
      - telehealth-network
    restart: unless-stopped

  # Authentication Service
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8001"
    env_file:
      - ./auth-service/.env
    networks:
      - telehealth-network
    restart: unless-stopped

  # Patient Service
  patient-service:
    build: ./patient-service
    ports:
      - "8002:8002"
    env_file:
      - ./patient-service/.env
    networks:
      - telehealth-network
    restart: unless-stopped

networks:
  telehealth-network:
    driver: bridge
