version: '3.8'

services:
  # API Gateway
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    env_file:
      - ./gateway/.env
    depends_on:
      - redis
    networks:
      - telehealth-network
    restart: unless-stopped

  # Redis for rate limiting and caching
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - telehealth-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Authentication Service
  auth-service:
    build: ./auth-service
    ports:
      - "8001:8001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - db
      - redis
    networks:
      - telehealth-network
    restart: unless-stopped

  # Patient Service
  patient-service:
    build: ./patient-service
    ports:
      - "8002:8002"
    env_file:
      - ./patient-service/.env
    depends_on:
      - db
      - auth-service
    networks:
      - telehealth-network
    restart: unless-stopped

  # Appointment Service
  appointment-service:
    build: ./appointment-service
    ports:
      - "8003:8003"
    env_file:
      - ./appointment-service/.env
    depends_on:
      - db
      - auth-service
      - patient-service
    networks:
      - telehealth-network
    restart: unless-stopped

  # Exercise Service
  exercise-service:
    build: ./exercise-service
    ports:
      - "8004:8003" # Map host 8004 to container 8003
    env_file:
      - ./exercise-service/.env
    depends_on:
      - db
      - auth-service # Assuming it might need auth later
      # Add other dependencies if needed (e.g., file-service)
    networks:
      - telehealth-network
    restart: unless-stopped

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telehealth_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - telehealth-network
    restart: unless-stopped

networks:
  telehealth-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
